version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - 2717:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  server:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - app-network
  client:
    build: ./client
    ports:
      - '8080:8080'
    networks:
      - app-network
volumes:
  mongo-data: 
networks:
  app-network:
    driver: bridge